package.json, src/DomainServer.ts, src/Vircadia.ts, src/domain/AssignmentClient.ts, src/domain/shared/Signal.ts
- Provide DS and AC states' types in the public API.
- Provide Signal class in the public API.
QA: Successfully use in the Web app.
=> Provide connection state types and Signal class in the API

package.json, src/Vircadia.ts
Waiting on the following to be merged:
=> Update version number to 0.0.4

src/domain/networking/udt/Socket.ts
Fixes build error introduced through interaction of two recent merges.
=> Fix build error.

src/domain/audio-client/AudioClient.ts, src/domain/audio/InboundAudioStream.ts
Reduces the amount of console log output.
=> Log certain warnings only once.

example/interface.html, example/interface.js, src/domain/avatar-renderer/ScriptAvatar.ts, src/domain/avatars/AvatarData.ts, src/domain/avatars/AvatarHashMap.ts, src/domain/interfaces/MyAvatarInterface.ts, src/domain/networking/packets/AvatarData.ts, src/domain/networking/packets/BulkAvatarData.ts, src/domain/shared/GLMHelpers.ts, src/domain/shared/SpatiallyNestable.ts, tests/domain/avatar-renderer/ScriptAvatar.unit.test.js, tests/domain/networking/packets/AvatarData.unit.test.js, tests/domain/networking/packets/BulkAvatarData.unit.test.js, tests/domain/shared/GLMHelpers.unit.test.js, tests/domain/shared/SpatiallyNestable.unit.test.js
- The orientation of the user's avatar in the domain is reported and can be set.
- The orientation of other avatars in the domain are reported.
- The example app provides these orientations as yaws.
=> Add avatar orientations in MyAvatarInterface and AvatarListInterface.

src/domain/networking/MessageData.ts, src/domain/networking/NLPacketList.ts, tests/domain/networking/packets/AvatarIdentity.unit.test.js, tests/domain/networking/packets/MessagesData.unit.test.js, tests/domain/networking/packets/MessagesSubscribe.unit.test.js, tests/domain/networking/packets/MessagesUnsubscribe.unit.test.js
=> Fix trailing 0s being sent in NLPacketList packets.

example/interface.html, example/interface.js, src/DomainServer.ts, src/EntityServer.ts, src/Vircadia.ts, tests/EntityServer.integration.test.js, tests/EntityServer.unit.test.js, tests/Vircadia.integration.test.js
Add EntityServer class that connects to the domain server.
=> Add entity server class

example/interface.html, example/interface.js, src/AvatarMixer.ts, src/Camera.ts, src/Vircadia.ts, src/domain/avatars/AvatarData.ts, src/domain/networking/packets/AvatarQuery.ts, src/domain/networking/packets/PacketScribe.ts, src/domain/networking/udt/PacketHeaders.ts, src/domain/shared/Camera.ts, src/domain/shared/GLMHelpers.ts, src/domain/shared/Vec3.ts, tests/AvatarMixer.integration.test.js, tests/AvatarMixer.unit.test.js, tests/Camera.unit.test.js, tests/Vircadia.integration.test.js, tests/domain/networking/packets/AvatarQuery.unit.test.js, tests/domain/networking/packets/PacketScribe.unit.test.js, tests/domain/shared/Camera.unit.test.js, tests/domain/shared/GLMHelpers.unit.test.js, tests/domain/shared/Vec3.unit.test.js
=> Request avatar data

src/DomainServer.ts, src/EntityServer.ts, src/domain/networking/packets/EntityData.ts, src/domain/networking/packets/PacketScribe.ts, src/domain/networking/udt/PacketHeaders.ts, src/domain/octree/OctreePacketProcessor.ts
=> Handle entity data packets.

example/interface.html, example/interface.js, src/domain/audio/AudioWorklets.ts, src/domain/avatar-renderer/ScriptAvatar.ts, src/domain/avatars/AvatarData.ts, src/domain/interfaces/AvatarListInterface.ts, src/domain/interfaces/MyAvatarInterface.ts, src/domain/networking/packets/AvatarData.ts, src/domain/networking/packets/BulkAvatarData.ts, src/domain/octree/OctreeConstants.ts, src/domain/shared/BitVectorHelpers.ts, src/domain/shared/Quat.ts, tests/domain/avatar-renderer/ScriptAvatar.unit.test.js, tests/domain/networking/packets/AvatarData.unit.test.js, tests/domain/networking/packets/BulkAvatarData.unit.test.js, tests/domain/shared/BitVectorHelpers.unit.test.js, tests/domain/shared/Quat.unit.test.js
Also fixes up receiving and providing other avatar's joint data from avatar mixer.
And adds "echo" checkboxes to make your avatar a doppelganger of another (model, scale, position, orientation, and joints).
=> Add ability to send own avatar joint data to avatar mixer.

src/domain/entities/ModelEntityItem.ts, tests/domain/entities/ModelEntityItem.unit.test.js
This PR fixes how model entity's properties related to joint rotations and joint translations are read.
=> Fix Model entity reading method

src/domain/entities/EntityTypes.ts, src/domain/entities/ImageEntityItem.ts, src/domain/entities/ModelEntityItem.ts, src/domain/entities/ShapeEntityItem.ts, src/domain/entities/TextEntityItem.ts, src/domain/networking/packets/EntityData.ts, src/domain/shared/Color.ts, src/domain/shared/Rect.ts, tests/domain/entities/ImageEntityItem.unit.test.js, tests/domain/entities/ShapeEntityItem.unit.test.js, tests/domain/entities/TextEntityItem.unit.test.js, tests/domain/networking/packets/EntityData.unit.test.js
Code review changes made on top of PR https://github.com/vircadia/vircadia-web-sdk/pull/146 .
=> Add Image and Text entity reading.

jsdoc/dev-mainpage.md, jsdoc/sdk-mainpage.md, src/domain/audio/AudioInput.ts, src/domain/entities/ImageEntityItem.ts, src/domain/entities/ModelEntityItem.ts, src/domain/entities/ShapeEntityItem.ts, src/domain/entities/TextEntityItem.ts, src/domain/networking/NLPacketList.ts, src/domain/networking/packets/EntityData.ts, src/domain/shared/Quat.ts, src/domain/shared/Vec3.ts, tests/domain/entities/ModelEntityItem.unit.test.js, tests/domain/networking/packets/EntityData.unit.test.js
- Return `""` instead of `undefined` for zero-length string properties read from entity data.
- Documentation tidying.
=> Return `""` instead of `undefined` for zero-length string properties read; documentation tidying.

src/domain/AvatarManager.ts, src/domain/avatar/MyAvatar.ts, src/domain/avatars/AvatarData.ts, src/domain/interfaces/AvatarListInterface.ts
Builds on top of: https://github.com/vircadia/vircadia-web-sdk/pull/162
=> Fix Uuid user documentation links.

tests/domain/networking/packets/EntityData.unit.test.js
Builds on top of: https://github.com/vircadia/vircadia-web-sdk/pull/163
=> Add unit tests for reading Web and Light entity packets.

src/domain/entities/AmbientLightPropertyGroup.ts, src/domain/entities/BloomPropertyGroup.ts, src/domain/entities/EntityTypes.ts, src/domain/entities/HazePropertyGroup.ts, src/domain/entities/ImageEntityItem.ts, src/domain/entities/KeyLightPropertyGroup.ts, src/domain/entities/LightEntityItem.ts, src/domain/entities/MaterialEntityItem.ts, src/domain/entities/ModelEntityItem.ts, src/domain/entities/ParticleEffectEntityItem.ts, src/domain/entities/ShapeEntityItem.ts, src/domain/entities/SkyboxPropertyGroup.ts, src/domain/entities/TextEntityItem.ts, src/domain/entities/WebEntityItem.ts, src/domain/entities/ZoneEntityItem.ts, src/domain/networking/packets/EntityData.ts, src/domain/shared/AvatarPriorityMode.ts, src/domain/shared/ComponentMode.ts, src/domain/shared/ShapeType.ts, tests/domain/entities/ModelEntityItem.unit.test.js, tests/domain/entities/ParticleEffectEntityItem.unit.test.js, tests/domain/entities/ZoneEntityItem.unit.test.js, tests/domain/networking/packets/EntityData.unit.test.js, tests/domain/shared/AvatarPriorityMode.unit.test.js, tests/domain/shared/ComponentMode.unit.test.ts, tests/domain/shared/ShapeType.unit.test.js
Builds on top of: https://github.com/vircadia/vircadia-web-sdk/pull/165
=> Add ParticleEffect entity reading.

src/domain/networking/DomainHandler.ts, src/domain/networking/LimitedNodeList.ts, src/domain/networking/NodeList.ts, src/domain/networking/packets/DomainServerAddedNode.ts, src/domain/networking/packets/PacketScribe.ts, src/domain/networking/udt/PacketHeaders.ts, src/domain/networking/udt/Socket.ts, src/domain/networking/webrtc/WebRTCDataChannel.ts, src/domain/networking/webrtc/WebRTCSignalingChannel.ts, src/domain/networking/webrtc/WebRTCSocket.ts, tests/domain/networking/DomainHandler.unit.test.js, tests/domain/networking/packets/DomainList.unit.test.js, tests/domain/networking/packets/DomainServerAddedNode.unit.test.js, tests/domain/networking/packets/PacketScribe.unit.test.js, tests/domain/networking/webrtc/WebRTCDataChannel.integration.test.js
Builds on top of PR: https://github.com/vircadia/vircadia-web-sdk/pull/172
=> Handle network interruptions.

src/domain/avatars/AvatarHashMap.ts
Add code missed from avatar traits implementation.
=> Delete traits for removed avatar.

src/domain/audio-client/AudioClient.ts, src/domain/audio/InboundAudioStream.ts, src/domain/networking/webrtc/WebRTCDataChannel.ts
Inserts silent samples in place of missing packets.
=> Handle audio output packet sequencing.

src/domain/entities/ImageEntityItem.ts
The data position was missing some increments which I've added and it now resolves this issue.
Should resolve #244
=> Fix for the subImage property on image entities not getting set correctly.

.gitignore, src/domain/networking/FingerprintUtils.ts, src/domain/shared/ModerationFlags.ts, tests/domain/networking/FingerprintUtils.unit.test.js, tests/domain/shared/Uuid.unit.test.js
Also, an incomplete solution is included for the Node environment.
=> Add fingerprint code for browser environment.

src/DomainServer.ts, src/Vircadia.ts, src/domain/AssignmentClient.ts
Export further types required by the Web App.
Fixes #270.
=> Export missing types.
